version: "3.8"

services:
  db:
    image: postgres:12
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark

  app:
    container_name: maga_wish_app
    restart: always
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8000:8000"
    volumes:
        - ./maga_wish:/app/maga_wish
    environment:
      - PYTHONUNBUFFERED=1
      - PROJECT_NAME=maga_wish
      - POSTGRES_SERVER=db
      - POSTGRES_USER=root

volumes:
  db: